version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/ourDorm_front"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/ourDorm_back"
    schedule:
      interval: "weekly"

